name: ms-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      PROJECT_FILE_PATH: build/lltool.vcxproj
      TEST_PROJECT_FILE_PATH: build/lltool-test.vcxproj
      BUILD_CONFIGURATION: Release
      TEST_BUILD_CONFIGURATION: Release
      BUILD_PLATFORM: x64

    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\\vcpkg\\bootstrap-vcpkg.bat
        .\\vcpkg\vcpkg integrate install
        .\\vcpkg\vcpkg install fmt:x64-windows

    - name: Build-App
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.PROJECT_FILE_PATH}} -t:rebuild -p:Configuration=${{env.BUILD_CONFIGURATION}} -p:Platform=${{env.BUILD_PLATFORM}}

    - name: Build-Unit-Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.TEST_PROJECT_FILE_PATH}} -t:rebuild -p:Configuration=${{env.TEST_BUILD_CONFIGURATION}} -p:Platform=${{env.BUILD_PLATFORM}}

    - name: Run-Unit-Tests
      working-directory: build/bin/win-${{env.BUILD_PLATFORM}}-${{env.TEST_BUILD_CONFIGURATION}}
      run: |
        dir .
        ./lltool-test.exe
